name: Documentation improvement
description: Request a docs clarification, correction, or new guide.
labels: ["docs", "needs-triage"]
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight
      options:
        - label: I searched existing issues and did not find a duplicate docs request.
          required: true

  - type: textarea
    id: location
    attributes:
      label: Affected documentation
      description: Link file/path/section that needs improvement.
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: Requested change
      description: What should be clarified, corrected, or added?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why this matters
      description: What confusion or failure does this currently cause?

  - type: textarea
    id: references
    attributes:
      label: Supporting references
      description: Optional examples, screenshots, or related links.
